Chess_Game.py

chess game

---

code for finding the SQUARE ROOT  of any no.cpp

CODE TO FIND THE SQUARE ROOT OF ANY NO. UP TO TWO FLOATING DIGIT USING C++.
PLS ACCEPT MY PUUL REQUEST AND ALSO GIVE  HACTOBERFEST LABLES.
THANK YOU..

Create code for finding the SQUARE ROOT  of any no.cpp

---

DEQUEUE.cpp

In this pull request i have added deque code . please accept my pull request. Thank you.

added deque code

---

Largest_subarray_with_unique_integers.cpp

Solution for the task using variable sliding window technique.
Coded in C++ language

Longest Subarray with unique integers

---

SpiralMatrix.cpp

It prints the matrix in spiral order

SpiralMatrix.cpp

---

Airline Registration System/Airline Registration System.cpp

Airline Registration System project made in c++

Airline Registration System.

---

kadane_algorithm.cpp

Added the file for kadane's algorithm

Added Kadane's Algorithm

---

MaxNumDiv3.cpp

In this, The input will be a list of numbers and this code will print a number which is created from the given digits and show maximum of it.. 
Please confirm it under hacktoberfest2022

Made a code for getting maximum no.divisble by 3

---

josephusproblem.cpp

This PR is made in context of hactoberfest 2022

Added the solution of josephus problem

---

Sort an array of 0s, 1s and 2s

Create Sort an array of 0s, 1s and 2s

---

Find all triplets with zero sum

Create Find all triplets with zero sum

---

Binary Tree in Vertical Order

Create Binary Tree in Vertical Order

---

Traversals Of Binary Tree

Create Traversals Of Binary Tree

---

check if tree is Sum tree or Not

Create check if tree is Sum tree or Not

---

Find duplicates in Array in O(N) time

Create Find duplicates in Array in O(N) time

---

Credit Card Validator/credit card validator solution.cpp

Credit Card Validator project made in C++ programming language

Credit Card Validator

---

TKINTER_QR_CODE.py

It is a simple python Tkinter program which takes length of password as argument and displays the QR code of the generated password.

QR X Password generator

---

CPP Problems/Array/SubarrayWithZeroSum.cpp
valid_palindrome

Subarray with zero-sum using maps

Another solution for subarray with zero sum

---

Binary_to_decimal.java

Added code to convert Binary to decimal using java

Binary to decimal conversion using java

---

armstrongNumber.java

Armstrong Number

---

Indian_flag.py

Please review my code and accept my PR under hactoberfest accepted.

Added a Indian flag program in python

---

CPP Problems/heap sort.cpp

i added the heap sort algo using cpp

Create heap sort.cpp

---

Insertion Sort.java
Merge Sort.java
Quick Sort.java

I would request you to add up by PR as well!

Added up Three Sorting Techniques

---

guess_the_number.cpp

question is about geussing the right number from the consequences

added a cp question

---

CPP Problems/Array/SubTask.cpp

Question Link: https://www.codechef.com/submit/SUBTASK

Added SubTask.cpp

---

Adding code for merging two sorted linked lists.
Adding code to merge two sorted linked lists.

I am adding a code to merge two sorted linked lists.

Tamanna verma99 patch 1

---

Segment-Tree.cpp

Adding working code of Segment Tree.

Added Segment Tree CPP code

---

codeforce/279 A solution.cpp

https://codeforces.com/contest/490/problem/A
this is the link of question and i have added its soln

Create 279 A solution.cpp

---

Course_Schedule_2.cpp

Added solution of course schedule 2 of leetcode

Added Course_Schedule_2.cpp

---

CPP Problems/Quiz game

this is quiz program in which user can give answer of some question related to programming. This program is python program.

Quiz  game in python

---

Graphs.py

implementation of graph in python with reachability matrix

Graphs in python

---

CPP Problems/stack/InfixToPostfixConversion.cpp
CPP Problems/stack/NextGreaterElement.cpp
CPP Problems/stack/TrappingRainWater.cpp

Added stack problems
1. Next Greater Element: gives next greater element for each array element.
2. Trapping Rain Water: Famous stack problem to find maximum amount of water trapped between blocks of various heights.
3. Infix To Postfix Conversion : converts a given infix expression to its postfix form.

Added standard stack problems

---

flattenBinaryTreeIntoLinkedList/Approach1.cpp
flattenBinaryTreeIntoLinkedList/Approach2.cpp
flattenBinaryTreeIntoLinkedList/Approach3.cpp

These Approaches are increasing level of optimization in case of Space Complexity.
And uses the most important concept of Morris Traversal
Kindly Merge my request.

Added Three Approaches to Flatten a Binary Tree to Linked List

---

doublyLinkedList.java

please add my file into your repository with label hactoberfest

hactoberfest-2022`

---

QueueImplimentation.cpp
StackImplimentaion.cpp

Implemented Stack using Array in c++ , and tested on sample test cases

Created Stack Implimentaion

---

DoublyLinkedListImplementation.cpp
SinglyLinkedListImplementation.cpp

Implemented Doubly Linked List using oops

Created Implementation of Doubly LinkedList

---

CircularLinkedListImplementation.cpp

Implemented circular linked list and added code of it's operations in c++.

Create Implementation of  Circular Linked List
